#! /bin/sh
### BEGIN INIT INFO
# Provides:          single
# Required-Start:    $remote_fs $named $network $time
# Required-Stop:     $remote_fs $named $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: radosgw
### END INIT INFO

. /lib/lsb/init-functions

CLIENT_NAME=client.radosgw.`hostname -s`
USER=www-data
DAEMON=/usb/bin/radosgw
CONF_FILE=/etc/ceph/ceph.conf


do_start () {
# Need log integration
#        start-stop-daemon --start --quiet --oknodo --chuid $USER --exec $DAEMON -- -c $CONF_FILE -n $CLIENT_NAME 
        su -u $USER -c "$DAEMON -c $CONF_FILE -n $CLIENT_NAME >> /var/log/radosgw/radosgw.log 2>&1 &"
}

case "$1" in
  start)
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        # No-op
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
